[package]
name = "elp_base_db"
edition.workspace = true
version.workspace = true

[lib]
doctest = false

[lints]
workspace = true

[dependencies]
elp_project_model.workspace = true
elp_syntax.workspace = true
elp_windows.workspace = true

anyhow.workspace = true
dashmap.workspace = true
dissimilar.workspace = true
eetf.workspace = true
either.workspace = true
fxhash.workspace = true
lazy_static.workspace = true
log.workspace = true
paths.workspace = true
profile.workspace = true
ra_ap_query-group-macro.workspace = true
regex.workspace = true
salsa.workspace = true
serde_json.workspace = true
tracing.workspace = true
stdx.workspace = true
vfs.workspace = true

[dev-dependencies]
expect-test.workspace = true
